### ISSUE TITLE
Tests not calling named arguments

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/swift-mathBoolOpConSwitch-lab#11]
![image](https://cloud.githubusercontent.com/assets/4515/20111107/0d0e4dcc-a5b5-11e6-8752-aa943e38f208.png)

**Comment by aviflombaum** [comment]
You could use an unnamed argument to get around this but I don't think the instructions suggest that unless you expect someone to infer that from the tests.

**Comment by JimCampagno** [comment]
Closing issue as this has been addressed. Thanks!
