### ISSUE TITLE
Function calls failing

### ISSUE THREAD

**Issue by Chrisb616** [learn-co-curriculum/swift-mathBoolOpConSwitch-lab#5]
In the Fun with Basics lessons, in the VCTests.swift file, all of the functions are called in a way that may be incorrect, at least as far as we were taut in the Functions and Multiple Arguments lessons.

After completing the lab, I ran the test and I got a slew of errors in the test file, either reading "Missing argument label" or "Extraneous argument label". It's because either the first argument had a label on it, or there were no labels at all. From my understanding there should be no label on the first argument and labels on all subsequent ones.

I'm not sure if this is something I'm doing wrong or not, but I thought I would bring it to your attention. I'm going to edit the test file so I can pass the test. If this is not the right thing to do, please let me know!

**Comment by JimCampagno** [comment]
@Chrisb616 You are correct. This was just fixed thanks to the wonderful @Lukeghenco who submitted a pull request with the updated changes. 

This lab had a few people working on it--and I didn't double-check that everything was working property (my bad!). Please keep raising issues like this moving forward as it helps us out a lot! I really appreciate it.. thanks SOO MUCH! :)
