### ISSUE TITLE
testing did not register with learn (previous tests in "ios new" prework have registered successfully).

### ISSUE THREAD

**Issue by wsrobins** [learn-co-curriculum/swift-mathBoolOpConSwitch-lab#9]

**Comment by AnnJohn** [comment]
hi @wsrobins thanks for raising the issue. We'll look into this.

@JimCampagno can you see if this also the same issue as previous lights issue.

**Comment by JimCampagno** [comment]
Fixing this now, will post a comment here when I'm done.

@AnnJohn @wsrobins

**Comment by JimCampagno** [comment]
This should be fixed. It has also been updated to work with Swift 3.0 & Xcode 8 which means you should go to the Mac App Store and update your Xcode @wsrobins.

I will be closing this issue, let me know if you have any problems moving forward! Please open up another issue here if it still isn't working for you but I have tested it on my end and it worked (with what I had just done).

@wsrobins  @AnnJohn
